# docker-compose.yml file

services:

  db:
    image: ${mfregistry:-metasfresh}/metas-db:$mfversion-preloaded
    ports:
      - "15432:5432"
<<<<<<< HEAD
    environment:      
=======
    environment:
>>>>>>> 3091b8e938a (externalSystems-Leich+Mehl can invoke a customizable postgREST reports (#19521))
      # run the database on the initial data
      # so we can later commit it again to create postcucumber images without doubling the image size
      - PGDATA=/var/lib/postgresql/initdata
    healthcheck:
      test: pg_isready -h localhost -U metasfresh -d metasfresh -t 1
      interval: 5s
      timeout: 2s
      start_period: 10s
      retries: 120
    deploy:
      mode: replicated
      replicas: 1
      
  rabbitmq:
    image: rabbitmq:3.9.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=metasfresh
      - RABBITMQ_DEFAULT_PASS=metasfresh
      - RABBITMQ_DEFAULT_VHOST=/
    deploy:
      mode: replicated
      replicas: 1

  cucumber:
    image: ${mfregistry:-metasfresh}/metas-cucumber:$mfversion
<<<<<<< HEAD
=======
    environment:
      - TEST_SMTP_HOST=$TEST_SMTP_HOST
      - TEST_SMTP_FROM=$TEST_SMTP_FROM
      - TEST_SMTP_USER=$TEST_SMTP_USER
      - TEST_SMTP_PASSWORD=$TEST_SMTP_PASSWORD
>>>>>>> 3091b8e938a (externalSystems-Leich+Mehl can invoke a customizable postgREST reports (#19521))
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./cucumber:/reports
    deploy:
      mode: replicated
      replicas: 1
    # uncomment and adjust 'command:' below to filter cucumber test runs
    # make sure 'command:' is using the same indentation level as 'deploy:'
    # for a complete list of available cucumber properties see: https://cucumber.io/docs/cucumber/api/?lang=java#list-configuration-options
    command: ${cucumberparams:-}

  bouncer:
    image: busybox
<<<<<<< HEAD
    command: "/bin/sh -c 'sleep 110m && echo \"Who of you folks wound the clock? It is really time to stop!\" && echo \"timeout: aborting cucumber run after 110 minutes\"'"
=======
    command: "/bin/sh -c 'sleep 180m && echo \"Who of you folks wound the clock? It is really time to stop!\" && echo \"timeout: aborting cucumber run after 110 minutes\"'"
>>>>>>> 3091b8e938a (externalSystems-Leich+Mehl can invoke a customizable postgREST reports (#19521))

volumes: {}
configs: {}
secrets: {}
